# Generated by Django 3.0.6 on 2020-05-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickyeats_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
