# Generated by Django 3.0.6 on 2020-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickyeats_app', '0002_party_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
