# Generated by Django 3.0.6 on 2020-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickyeats_app', '0002_auto_20200521_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='search_query',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
