# Generated by Django 3.0.6 on 2020-05-27 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickyeats_app', '0004_matchedrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedrestaurant',
            name='matched_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_restaurants', to='pickyeats_app.MatchedRestaurant'),
        ),
        migrations.AlterField(
            model_name='likedrestaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='pickyeats_app.Party'),
        ),
    ]
